### ISSUE TITLE
Feature request: add colorfunc to argument to m_style_surface() and others

### ISSUE THREAD

**Issue by cwbcm** [swsoyee/r3dmol#47]
Hi,

Great package! I would like to color structures with customized values, like discussed in #45. The colorfunc argument is only available in m_style_cartoon but not other representation styles. I wonder if it is possible to add this argument to m_style_surface(), m_style_sphere() and m_style_stick(). 

Thank you!

**Comment by swsoyee** [comment]
Hi, I have add `colorfunc` to `m_style_sphere()`, `m_style_ballnstick`, and `m_style_stick()`.
Since the implementation of `*_surface()` is a little bit different from others in the original 3Dmol.js, this additional parameter could not be provided in a short time.

Install the latest development version:

```r
# install.packages("devtools")
devtools::install_github("swsoyee/r3dmol")
```

Example:
```r
make_colours <- function(x, start = "red", end = "green") {
  colorfun <- colorRampPalette(c(start, end))
  
  paste0('"', paste(colorfun(x), collapse = '", "'), '"')
}


r3dmol() %>%
  m_add_model(data = pdb_1j72) %>%
  m_set_style(style = m_style_stick(
    colorfunc = paste0("
        function(atom) {
          const color = [", make_colours(120, "blue", "tomato"),"]
          return color[Math.round(atom.b)]
        }")
  )) %>%
  m_zoom_to() %>%
  m_png()
```
![image](https://user-images.githubusercontent.com/20528423/184525063-8e0edca3-8a56-4fee-bc43-8015b5a65074.png)

```r
r3dmol() %>%
  m_add_model(data = pdb_1j72) %>%
  m_set_style(style = m_style_sphere(
    colorfunc = paste0("
        function(atom) {
          const color = [", make_colours(120, "blue", "tomato"),"]
          return color[Math.round(atom.b)]
        }")
  )) %>%
  m_zoom_to() %>%
  m_png()
```
![image](https://user-images.githubusercontent.com/20528423/184525068-b16dcedc-a9b3-4658-b3bb-635aeaefda79.png)

```r
r3dmol() %>%
  m_add_model(data = pdb_1j72) %>%
  m_set_style(style = m_style_ballnstick(
    colorfunc = paste0("
        function(atom) {
          const color = [", make_colours(120, "blue", "tomato"),"]
          return color[Math.round(atom.b)]
        }")
  )) %>%
  m_zoom_to() %>%
  m_png()
```

![image](https://user-images.githubusercontent.com/20528423/184525074-51ffdfdd-3637-4b96-b1c9-b8c901718dba.png)

**Comment by cwbcm** [comment]
Thanks for the quick response! The update works perfect
